FROM mcr.microsoft.com/mssql/server:2025-latest

USER root

RUN apt-get update && \
    apt-get install -y \
      gnupg gnupg2 gnupg1 curl apt-transport-https ca-certificates && \
    curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl -sSL https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2025.list \
      -o /etc/apt/sources.list.d/mssql-server-2025.list && \
    apt-get update && \
    apt-get install -y mssql-server-fts && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER mssql
